name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3

  # Adds Cupertino icons for iOS style widgets/icons
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices
  flutter_lints: ^5.0.0

flutter:

  # Ensures that Material Icons font is included
  uses-material-design: true

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend[wght].ttf
    - family: ZillaSlab
      fonts:
        - asset: assets/fonts/ZillaSlab-Regular.ttf
        - asset: assets/fonts/ZillaSlab-Bold.ttf

  # Define your app's assets (images for avatar and animal photos)
  assets:
    - assets/avatar.jpg
    - assets/birds.png
    - assets/carnivore.png
    - assets/herbivore.png
    - assets/seafish.png
    - assets/lion.jpg
    - assets/koala.jpg
    - assets/cheetah.jpg
    - assets/elephant.jpg
    - assets/tiger.jpg
    - assets/panda.jpg
    - assets/homewild.png
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/cartoon1.jpeg
    - assets/cartoon2.jpeg
    - assets/cartoon3.jpeg
    - assets/getstart1.jpg